### ISSUE TITLE
Aggiornamento file converti_api.c

### ISSUE THREAD

**Issue by MartinaPo** [AndreaRibuoli/EserciziC#2]
Buongiorno professore,

vorremmo chiedere se sarebbe possibile aggiornare il file **converti_api.c** con la versione più recente che abbiamo visto insieme (esempio: linee 14, 21, dalla 56 alla 59 risultano diverse). 

Per la precisione, abbiamo notato che i file converti.c e converti_api.c nel suo repository sono praticamente identici (converti_api.c include il comando "converti_api.h" ma per il resto sembra essere uguale a converti.c).

Link al file: https://github.com/AndreaRibuoli/EserciziC/blob/main/converti_api.c

**Comment by AndreaRibuoli** [comment]
Buongiorno Martina,
  ieri ho aggiornato il sorgente **converti_api.c** con una variante che dovrebbe supportare (con un unico sorgente) le diverse piattaforme. Oggi faremo le verifiche durante la FAD.

**Comment by AndreaRibuoli** [comment]
La funzione modificata dovrebbe operare correttamente sulle diverse piattaforme in uso.
