### ISSUE TITLE
Richiesta materiale integrativo

### ISSUE THREAD

**Issue by cdomizi** [AndreaRibuoli/EserciziC#3]
Salve Professore,

mi scuso per il ricorso a uno strumento non convenzionale per contattarla, ma non avevo altro modo di farlo direttamente.

Le scrivo perché, come avrà potuto constatare, a diverse delle sue lezioni non ho potuto partecipare. Per mettermi in pari con il programma ho consultato regolarmente questa repository e ho potuto contare sull'aiuto prezioso dei miei colleghi, i quali hanno condiviso molte informazioni e materiali utili. Sulla base di questo ho cercato di approfondire ed esercitarmi in autonomia, ma mi rendo conto di non averlo fatto in maniera esaustiva data la inevitabile lacunosità delle indicazioni ricevute. D'altronde, per quanto disponibili e collaborativi si siano dimostrati i colleghi, non posso certo fare affidamento esclusivo su di loro per un compito - tenermi aggiornato sul corso - cui non sono tenuti.

Confido quindi su di lei per ricevere materiale/bibliografia/indicazioni per mettermi in pari con il programma del corso. Al di là del motivo contingente del test in programma venerdì prossimo, l'esigenza di integrare e consolidare la mia preparazione è dettata dall'interesse per i contenuti del suo insegnamento e dall'importanza che credo siano destinati ad rivestire nel quadro generale della mia formazione di programmatore.

Ci tengo infine a specificare che le mie assenze sono dettate da cause di forza maggiore (impegni di lavoro concomitanti con l'orario delle lezioni, notevole distanza geografica dalla sede delle lezioni in presenza), ma gli organizzatori del corso mi hanno assicurato che sarei stato comunque messo in condizione di seguire con profitto il percorso formativo. Ciò comporta naturalmente un maggiore carico di lavoro individuale da parte mia, che sono volentieri disposto ad assumermi per ovviare al problema della frequenza.

Attendo sue e la ringrazio anticipatamente per la collaborazione.

Cesare Domizi

**Comment by AndreaRibuoli** [comment]
Gent.mo Cesare,

  spero tu sia al corrente che ad ogni presentazione io fornisco un pdf della traccia degli argomenti trattati a lezione.
Questi sono effettivamente un poco criptici per chi non abbia partecipato a lezione.

La mia visione è di fornirvi quante più informazioni di inquadramento (ecco perché il nome "fondamenti") confidando nella
possibilità che queste "lavorino" anche in futuro rimanendo un invito costante all'approfondimento.

Concretamente avevo già indicato come un buon compromesso per una introduzione alla programmazione (con uno studio individuale) il libro: 

* Brian W. Kernighan, Dennis M. Ritchie **The C Programming Language** (2nd edition) 

[ alcune versioni , anche in Italiano, sembrano disponibili come pdf in rete ]

tuttavia l'enfasi generale, ossia i "macro-obiettivi" che mi sono stati assegnati, richiedevano anche venisse affrontato
 il tema della organizzazione di software complesso per ottemperare il quale ho ritenuto vitale che poteste acquisire dimestichezza anche con la strutturazione del codice. Ecco perché  ho enfatizzato:

* l'utilità **make**, 
* la capacità di scrivere dei **Makefile**, 
* l'organizzazione delle funzioni all'interno delle **shared library** (note anche col nome di DLL).

In futuro il lavoro su Magento tenderà ad organizzare le conoscenze in maniera molto più specifica per tale piattaforma e saranno molto meno le ambiguità (ossia i gradi di libertà) nell'affrontare il vasto mondo di **Fondamenti di programmazione**.

Purtroppo in questo mio tentativo di offrirvi la mia panoramica il più possibile vasta (informazioni su diversi ambienti di
esecuzione, riferimenti ad altri linguaggi di programmazione, inquadramenti storici) non facilita certo la possibilità di compensare assenze ripetute.

Tuttavia, se Giovedì sarai presente, intervieni ed utilizziamo il tuo percorso come opportunità per un "ripasso" prima della prova di Venerdì. Altrimenti scrivimi pure quali parti dei pdf non ti sono chiare. Lo strumento può andare bene.
Un poco più di riservatezza può essere raggiunta con email dirette ( andrea.ribuoli@yahoo.com ).

Buona serata,

    Andrea

**Comment by AndreaRibuoli** [comment]
Prosegue via email dirette...
